sudo: false
language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
env: LDFLAGS="-L/usr/local/opt/openssl/lib" CPPFLAGS="-I/usr/local/opt/openssl/include"
addons:
  apt:
    packages:
    - libunbound-dev
    - libidn11-dev
    - libyaml-dev
    - check
    - libevent-dev
    - libev-dev
    - libuv-dev
    - valgrind
    - clang
    - wget
    - openssh-client
  homebrew:
    brewfile: true
script:
  - mkdir tests
  - cd tests
  - ../src/test/tpkg/run-all.sh
# - ../src/test/tpkg/run-one.sh 225-stub-only-valgrind-checks
